In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
import seaborn as sns
from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import copy, math
from sklearn.ensemble import RandomForestClassifier

In [12]:
rel_abd=pd.read_csv(r"E:\BT workshop\PTB\phylotypes\phylotype_relabd.1e0.csv")
metadata=pd.read_csv(r"E:\BT workshop\PTB\metadata\metadata.csv")

In [13]:
rel_abd.head()

,specimen,pt__00001,pt__00002,pt__00003,pt__00004,pt__00005,pt__00006,pt__00007,pt__00008,pt__00009,...,pt__01835,pt__01836,pt__01837,pt__01838,pt__01839,pt__01840,pt__01841,pt__01842,pt__01843,pt__01844
0,A00001-05,0.797900,0.023097,0.002100,0.008924,0.007349,0.000000,0.106037,0.0,0.009449,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,A00002-01,0.805641,0.000613,0.006131,0.042305,0.010423,0.000000,0.000613,0.0,0.001839,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,A00003-02,0.963299,0.000648,0.001079,0.000000,0.011658,0.000000,0.000216,0.0,0.001079,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,A00004-08,0.927544,0.000514,0.001028,0.009250,0.004625,0.000000,0.027235,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,A00004-12,0.806593,0.000366,0.000549,0.014286,0.000549,0.000366,0.142857,0.0,0.000916,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
metadata.index=[i for i in metadata['specimen']]

In [6]:
metadata.head()

,project,specimen,participant_id,was_term,delivery_wk,collect_wk,race,age,NIH Racial Category,NIH Ethnicity Category,was_preterm,was_early_preterm
A00001-05,A,A00001-05,A00001,False,38,33,American Indian,Unknown,American Indian or Alaska Native,Unknown,False,False
A00002-01,A,A00002-01,A00002,False,40,38,White,Unknown,White,Unknown,False,False
A00003-02,A,A00003-02,A00003,False,40,30,Asian-Japanese,Unknown,Asian,Unknown,False,False
A00004-08,A,A00004-08,A00004,False,40,27,White,Unknown,White,Unknown,False,False
A00004-12,A,A00004-12,A00004,False,40,29,White,Unknown,White,Unknown,False,False

In [27]:
metadata['was_preterm'].sum()/metadata.shape[0]

0.2764114030184461

In [15]:
columns=rel_abd.columns
len_col=len(columns)

In [16]:
rel_abd.index=[i for i in rel_abd['specimen']]

In [17]:
rel_abd.drop('specimen',inplace=True,axis=1)

In [18]:
rel_abd.head()

,pt__00001,pt__00002,pt__00003,pt__00004,pt__00005,pt__00006,pt__00007,pt__00008,pt__00009,pt__00010,...,pt__01835,pt__01836,pt__01837,pt__01838,pt__01839,pt__01840,pt__01841,pt__01842,pt__01843,pt__01844
A00001-05,0.797900,0.023097,0.002100,0.008924,0.007349,0.000000,0.106037,0.0,0.009449,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00002-01,0.805641,0.000613,0.006131,0.042305,0.010423,0.000000,0.000613,0.0,0.001839,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00003-02,0.963299,0.000648,0.001079,0.000000,0.011658,0.000000,0.000216,0.0,0.001079,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00004-08,0.927544,0.000514,0.001028,0.009250,0.004625,0.000000,0.027235,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00004-12,0.806593,0.000366,0.000549,0.014286,0.000549,0.000366,0.142857,0.0,0.000916,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
rel_abd[rel_abd<0.001]=0

In [12]:
rel_abd.head()

,pt__00001,pt__00002,pt__00003,pt__00004,pt__00005,pt__00006,pt__00007,pt__00008,pt__00009,pt__00010,...,pt__01835,pt__01836,pt__01837,pt__01838,pt__01839,pt__01840,pt__01841,pt__01842,pt__01843,pt__01844
A00001-05,0.797900,0.023097,0.002100,0.008924,0.007349,0.0,0.106037,0.0,0.009449,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00002-01,0.805641,0.000000,0.006131,0.042305,0.010423,0.0,0.000000,0.0,0.001839,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00003-02,0.963299,0.000000,0.001079,0.000000,0.011658,0.0,0.000000,0.0,0.001079,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00004-08,0.927544,0.000000,0.001028,0.009250,0.004625,0.0,0.027235,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00004-12,0.806593,0.000000,0.000000,0.014286,0.000000,0.0,0.142857,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
groups = rel_abd.groupby(rel_abd.index.str[0])
result = {}
for name, group in groups:
    mask = group > 0
    col_means = mask.mean()[mask.mean() >= 0.5]
    result[name] = col_means.index.values

In [25]:
result

{'A': array(['pt__00001', 'pt__00003', 'pt__00004', 'pt__00005', 'pt__00007',
        'pt__00009', 'pt__00013', 'pt__00017', 'pt__00018', 'pt__00032',
        'pt__00049'], dtype=object),
 'B': array(['pt__00001'], dtype=object),
 'C': array(['pt__00001', 'pt__00002', 'pt__00004', 'pt__00005'], dtype=object),
 'D': array(['pt__00001'], dtype=object),
 'E': array(['pt__00047', 'pt__00090', 'pt__00113', 'pt__00118', 'pt__00206',
        'pt__00716'], dtype=object),
 'F': array(['pt__00024'], dtype=object),
 'G': array(['pt__00001', 'pt__00002', 'pt__00003', 'pt__00004', 'pt__00005',
        'pt__00006', 'pt__00007', 'pt__00009', 'pt__00010'], dtype=object),
 'H': array(['pt__00001'], dtype=object),
 'I': array(['pt__00001', 'pt__00002', 'pt__00003', 'pt__00004', 'pt__00010'],
       dtype=object),
 'J': array(['pt__00001'], dtype=object)}

In [14]:
result = list(set(result))

In [15]:
result

['pt__00047',
 'pt__00113',
 'pt__00017',
 'pt__00006',
 'pt__00010',
 'pt__00018',
 'pt__00049',
 'pt__00002',
 'pt__00716',
 'pt__00118',
 'pt__00003',
 'pt__00005',
 'pt__00206',
 'pt__00007',
 'pt__00001',
 'pt__00032',
 'pt__00004',
 'pt__00013',
 'pt__00009',
 'pt__00090',
 'pt__00024']

In [16]:
group_A = groups.get_group('A')

In [17]:
group_A

,pt__00001,pt__00002,pt__00003,pt__00004,pt__00005,pt__00006,pt__00007,pt__00008,pt__00009,pt__00010,...,pt__01835,pt__01836,pt__01837,pt__01838,pt__01839,pt__01840,pt__01841,pt__01842,pt__01843,pt__01844
A00001-05,0.797900,0.023097,0.002100,0.008924,0.007349,0.000000,0.106037,0.000000,0.009449,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00002-01,0.805641,0.000000,0.006131,0.042305,0.010423,0.000000,0.000000,0.000000,0.001839,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00003-02,0.963299,0.000000,0.001079,0.000000,0.011658,0.000000,0.000000,0.000000,0.001079,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00004-08,0.927544,0.000000,0.001028,0.009250,0.004625,0.000000,0.027235,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00004-12,0.806593,0.000000,0.000000,0.014286,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A00039-07,0.170783,0.003529,0.014820,0.001059,0.534933,0.001411,0.003881,0.002117,0.037050,0.001764,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00039-08,0.276435,0.016616,0.057905,0.000000,0.285498,0.000000,0.021148,0.002518,0.047835,0.002518,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00039-09,0.033268,0.003914,0.015656,0.000000,0.262231,0.003914,0.003914,0.001957,0.007828,0.011742,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00039-10,0.061573,0.011128,0.033383,0.000000,0.378338,0.000000,0.003709,0.001484,0.039318,0.014095,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A00039-12,0.552818,0.004882,0.057701,0.000000,0.162672,0.000000,0.001332,0.000000,0.017754,0.021971,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
selected_data = rel_abd[result]

In [19]:
selected_data

,pt__00047,pt__00113,pt__00017,pt__00006,pt__00010,pt__00018,pt__00049,pt__00002,pt__00716,pt__00118,...,pt__00005,pt__00206,pt__00007,pt__00001,pt__00032,pt__00004,pt__00013,pt__00009,pt__00090,pt__00024
A00001-05,0.0,0.0,0.006824,0.0,0.0,0.000000,0.002625,0.023097,0.0,0.0,...,0.007349,0.0,0.106037,0.797900,0.006299,0.008924,0.001575,0.009449,0.0,0.0
A00002-01,0.0,0.0,0.013489,0.0,0.0,0.044145,0.003679,0.000000,0.0,0.0,...,0.010423,0.0,0.000000,0.805641,0.009810,0.042305,0.000000,0.001839,0.0,0.0
A00003-02,0.0,0.0,0.000000,0.0,0.0,0.000000,0.005613,0.000000,0.0,0.0,...,0.011658,0.0,0.000000,0.963299,0.003022,0.000000,0.000000,0.001079,0.0,0.0
A00004-08,0.0,0.0,0.000000,0.0,0.0,0.020041,0.000000,0.000000,0.0,0.0,...,0.004625,0.0,0.027235,0.927544,0.000000,0.009250,0.000000,0.000000,0.0,0.0
A00004-12,0.0,0.0,0.000000,0.0,0.0,0.008425,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.142857,0.806593,0.003846,0.014286,0.001465,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
J00111-01,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
J00112-01,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.999644,0.000000,0.000000,0.000000,0.000000,0.0,0.0
J00113-01,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.038340,0.0,0.0,...,0.000000,0.0,0.000000,0.483433,0.000000,0.000000,0.000000,0.000000,0.0,0.0
J00115-01,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
J00116-01,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.832747,0.000000,0.000000,0.000000,0.000000,0.0,0.0

In [20]:
selected_data.to_csv('selected_data.csv', index=False)

In [21]:
selected_data.head()

,pt__00047,pt__00113,pt__00017,pt__00006,pt__00010,pt__00018,pt__00049,pt__00002,pt__00716,pt__00118,...,pt__00005,pt__00206,pt__00007,pt__00001,pt__00032,pt__00004,pt__00013,pt__00009,pt__00090,pt__00024
A00001-05,0.0,0.0,0.006824,0.0,0.0,0.000000,0.002625,0.023097,0.0,0.0,...,0.007349,0.0,0.106037,0.797900,0.006299,0.008924,0.001575,0.009449,0.0,0.0
A00002-01,0.0,0.0,0.013489,0.0,0.0,0.044145,0.003679,0.000000,0.0,0.0,...,0.010423,0.0,0.000000,0.805641,0.009810,0.042305,0.000000,0.001839,0.0,0.0
A00003-02,0.0,0.0,0.000000,0.0,0.0,0.000000,0.005613,0.000000,0.0,0.0,...,0.011658,0.0,0.000000,0.963299,0.003022,0.000000,0.000000,0.001079,0.0,0.0
A00004-08,0.0,0.0,0.000000,0.0,0.0,0.020041,0.000000,0.000000,0.0,0.0,...,0.004625,0.0,0.027235,0.927544,0.000000,0.009250,0.000000,0.000000,0.0,0.0
A00004-12,0.0,0.0,0.000000,0.0,0.0,0.008425,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.142857,0.806593,0.003846,0.014286,0.001465,0.000000,0.0,0.0

In [22]:
selected_data

,pt__00047,pt__00113,pt__00017,pt__00006,pt__00010,pt__00018,pt__00049,pt__00002,pt__00716,pt__00118,...,pt__00005,pt__00206,pt__00007,pt__00001,pt__00032,pt__00004,pt__00013,pt__00009,pt__00090,pt__00024
A00001-05,0.0,0.0,0.006824,0.0,0.0,0.000000,0.002625,0.023097,0.0,0.0,...,0.007349,0.0,0.106037,0.797900,0.006299,0.008924,0.001575,0.009449,0.0,0.0
A00002-01,0.0,0.0,0.013489,0.0,0.0,0.044145,0.003679,0.000000,0.0,0.0,...,0.010423,0.0,0.000000,0.805641,0.009810,0.042305,0.000000,0.001839,0.0,0.0
A00003-02,0.0,0.0,0.000000,0.0,0.0,0.000000,0.005613,0.000000,0.0,0.0,...,0.011658,0.0,0.000000,0.963299,0.003022,0.000000,0.000000,0.001079,0.0,0.0
A00004-08,0.0,0.0,0.000000,0.0,0.0,0.020041,0.000000,0.000000,0.0,0.0,...,0.004625,0.0,0.027235,0.927544,0.000000,0.009250,0.000000,0.000000,0.0,0.0
A00004-12,0.0,0.0,0.000000,0.0,0.0,0.008425,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.142857,0.806593,0.003846,0.014286,0.001465,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
J00111-01,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
J00112-01,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.999644,0.000000,0.000000,0.000000,0.000000,0.0,0.0
J00113-01,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.038340,0.0,0.0,...,0.000000,0.0,0.000000,0.483433,0.000000,0.000000,0.000000,0.000000,0.0,0.0
J00115-01,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
J00116-01,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.0,0.000000,0.832747,0.000000,0.000000,0.000000,0.000000,0.0,0.0

In [23]:

selected_data['was_term']=metadata['was_term']

C:\Users\THAZEEL\AppData\Local\Temp\ipykernel_12000\2616289319.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_data['was_term']=metadata['was_term']

In [24]:
selected_data['group']=selected_data.index.str[0]
selected_data.head()

C:\Users\THAZEEL\AppData\Local\Temp\ipykernel_12000\3828785057.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_data['group']=selected_data.index.str[0]

,pt__00047,pt__00113,pt__00017,pt__00006,pt__00010,pt__00018,pt__00049,pt__00002,pt__00716,pt__00118,...,pt__00007,pt__00001,pt__00032,pt__00004,pt__00013,pt__00009,pt__00090,pt__00024,was_term,group
A00001-05,0.0,0.0,0.006824,0.0,0.0,0.000000,0.002625,0.023097,0.0,0.0,...,0.106037,0.797900,0.006299,0.008924,0.001575,0.009449,0.0,0.0,False,A
A00002-01,0.0,0.0,0.013489,0.0,0.0,0.044145,0.003679,0.000000,0.0,0.0,...,0.000000,0.805641,0.009810,0.042305,0.000000,0.001839,0.0,0.0,False,A
A00003-02,0.0,0.0,0.000000,0.0,0.0,0.000000,0.005613,0.000000,0.0,0.0,...,0.000000,0.963299,0.003022,0.000000,0.000000,0.001079,0.0,0.0,False,A
A00004-08,0.0,0.0,0.000000,0.0,0.0,0.020041,0.000000,0.000000,0.0,0.0,...,0.027235,0.927544,0.000000,0.009250,0.000000,0.000000,0.0,0.0,False,A
A00004-12,0.0,0.0,0.000000,0.0,0.0,0.008425,0.000000,0.000000,0.0,0.0,...,0.142857,0.806593,0.003846,0.014286,0.001465,0.000000,0.0,0.0,False,A

In [29]:
train, test = train_test_split(selected_data, test_size=0.2, stratify=selected_data['group'])
train_groups = train.groupby('group')
test_groups = test.groupby('group')

In [30]:
models = {}
for group, group_data in train_groups:
    X = group_data.drop(['group', 'was_term'], axis=1)
    y = group_data['was_term']
    model = RandomForestClassifier()
    model.fit(X, y)
    models[group] = model

In [27]:
models = {}
for group, group_data in train_groups:
    X = group_data.drop(['group', 'was_term'], axis=1)
    y = group_data['was_term']
    model = RandomForestClassifier()
    model.fit(X, y)
    models[group] = model

In [31]:
predictions = []
true_labels = []
for group, group_data in test_groups:
    model = models[group]
    X = group_data.drop(['group', 'was_term'], axis=1)
    y = group_data['was_term']
    y_pred = model.predict(X)
    predictions.extend(y_pred)
    true_labels.extend(y)

In [32]:
accuracies = {}
for group, group_data in test_groups:
    y_true = true_labels[:len(group_data)]
    y_pred = predictions[:len(group_data)]
    accuracy = accuracy_score(y_true, y_pred)
    accuracies[group] = accuracy
    predictions = predictions[len(group_data):]
    true_labels = true_labels[len(group_data):]

In [33]:
for group, accuracy in accuracies.items():
    print(f'Group {group}: accuracy={accuracy}')

Group A: accuracy=0.9130434782608695
Group B: accuracy=0.7142857142857143
Group C: accuracy=0.896551724137931
Group D: accuracy=0.7777777777777778
Group E: accuracy=0.8235294117647058
Group F: accuracy=0.6206896551724138
Group G: accuracy=0.7277486910994765
Group H: accuracy=0.5581395348837209
Group I: accuracy=0.8156996587030717
Group J: accuracy=0.7647058823529411

In [28]:
for group, model in models.items():
    feature_names = X.columns
    importances = model.feature_importances_
    max_importance_index = importances.argmax()
    max_importance_feature = feature_names[max_importance_index]
    print(f'Group {group}: {max_importance_feature} (importance={importances[max_importance_index]})')

Group A: pt__00001 (importance=0.19467698255836755)
Group B: pt__00001 (importance=0.5524014739158938)
Group C: pt__00001 (importance=0.526277277308613)
Group D: pt__00001 (importance=0.36165467058617345)
Group E: pt__00047 (importance=0.2524163138979789)
Group F: pt__00024 (importance=0.22488924335944993)
Group G: pt__00001 (importance=0.18945516545461297)
Group H: pt__00001 (importance=0.22741103437573623)
Group I: pt__00001 (importance=0.2282970938227671)
Group J: pt__00001 (importance=0.8958033925543711)

In [62]:
# models = {}
# for group, group_data in train_groups:
#     X = group_data.drop(['group', 'was_term'], axis=1)
#     y = group_data['was_term']
#     model = LogisticRegression()
#     model.fit(X, y)
#     models[group] = model

In [65]:
# predictions = []
# for group, group_data in test_groups:
#     X = group_data.drop(['group', 'was_term'], axis=1)
#     y_true = group_data['was_term']
#     y_pred = models[group].predict(X)
#     predictions.extend(y_pred)
#     accuracy = accuracy_score(y_true, y_pred)
#     print(f'Group {group} accuracy: {accuracy}')

Group A accuracy: 0.8695652173913043
Group B accuracy: 0.7142857142857143
Group C accuracy: 0.8620689655172413
Group D accuracy: 0.8148148148148148
Group E accuracy: 0.7647058823529411
Group F accuracy: 0.6896551724137931
Group G accuracy: 0.7068062827225131
Group H accuracy: 0.6511627906976745
Group I accuracy: 0.8191126279863481
Group J accuracy: 0.7647058823529411

In [66]:
# y_true = test['was_term']
# accuracy = accuracy_score(y_true, predictions)
# print(f'Combined model accuracy: {accuracy}')

Combined model accuracy: 0.659217877094972

In [24]:
# X = selected_data[result]
# y = selected_data['was_term']
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# selected_data['group']=selected_data.index.str[0]

C:\Users\THAZEEL\AppData\Local\Temp\ipykernel_10608\1879277171.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_data['group']=selected_data.index.str[0]

In [25]:
# X_test

,pt__00090,pt__00716,pt__00032,pt__00047,pt__00018,pt__00013,pt__00017,pt__00001,pt__00206,pt__00024,...,pt__00113,pt__00118,pt__00003,pt__00005,pt__00006,pt__00009,pt__00002,pt__00049,pt__00007,pt__00010
G00006-07,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
I00258-03,0.00000,0.000000,0.0,0.000000,0.000000,0.001889,0.0,0.882700,0.000000,0.0,...,0.000000,0.000000,0.004152,0.002757,0.029065,0.001923,0.011997,0.0,0.001208,0.002059
G00083-05,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.008918,0.000000,0.0,...,0.000000,0.000000,0.043378,0.022740,0.460429,0.018025,0.156579,0.0,0.029353,0.055143
D00097-02,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.113807,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.017368,0.038521,0.0,0.434818,0.000000
G00091-14,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.950724,0.000000,0.0,...,0.000000,0.000000,0.002209,0.000000,0.018088,0.001425,0.004800,0.0,0.000000,0.001443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C00082-01,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
I00352-01,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.346203,0.000000,0.0,...,0.000000,0.000000,0.062613,0.033484,0.000000,0.003180,0.004193,0.0,0.017036,0.000000
E00024-04,0.03551,0.176735,0.0,0.175102,0.000000,0.000000,0.0,0.000000,0.015918,0.0,...,0.033061,0.345714,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
I00054-01,0.00000,0.000000,0.0,0.000000,0.002635,0.000000,0.0,0.801886,0.000000,0.0,...,0.000000,0.000000,0.058177,0.000000,0.000000,0.002315,0.031865,0.0,0.010973,0.001807
F00035-02,0.00000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.005106,0.000000,0.000000,0.000000,0.0,0.000000,0.000000

In [26]:
# models = {}
# for group in selected_data['group'].unique():
#     group_data = selected_data[selected_data['group'] == group]
#     group_X_train = X_train[X_train.index.isin(group_data.index)]
#     group_y_train = y_train[y_train.index.isin(group_data.index)]
#     model = LogisticRegression()
#     model.fit(group_X_train, group_y_train)
#     models[group] = model

In [27]:
# predictions = pd.DataFrame(index=X_test.index, columns=selected_data['group'].unique())
# for group in predictions.columns:
#     group_data = selected_data[selected_data['group'] == group]
#     group_X_test = X_test[X_test.index.isin(group_data.index)]
#     predictions[group] = models[group].predict(group_X_test)

ValueError: Length of values (55) does not match length of index (716)